name: getx_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^6.2.0
  get: ^4.6.5
  shared_preferences: ^2.0.18
  hero_text: ^0.0.1

  dio: ^5.0.2

  google_books_api:
    path: ./packages/google_books_api
  flutter_staggered_grid_view: ^0.6.2
  url_launcher: ^6.1.10
  auto_size_text: ^3.0.0
  expandable_text: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
